### ISSUE TITLE
Nuxt built in composable missing

### ISSUE THREAD

**Issue by v3nt** [divasilevski/nuxt-starter#9]
For example if I try to test `app.vue` which has `useHead` we get this error.

Test example

https://github.com/v3nt/nuxt-starter/blob/bug/useIssues/tests/app.spec.ts

```
 FAIL  tests/app.spec.ts [ tests/app.spec.ts ]
ReferenceError: useHead is not defined
 ❯ setup app.vue:8:1
      6| 
      7| <script lang="ts" setup>
      8| useHead({
       | ^
      9|   title: 'Nuxt app',
     10|   htmlAttrs: { lang: 'en' },
```

**Comment by divasilevski** [comment]
Hi, you need to import useHead. You can use auto-import in vitest.config.ts.
`imports: ['vitest', 'vue', 'vue-router', { '@unhead/vue': ['useHead'] }],`
